利用者名、ルーム名、チャットの入力制限を追加
RuiFujita/web_chat_app pull request #1
Opened 2023-03-06 04:09 UTC by RuiFujita

### **レビュー希望納期**
2023/03/07

### **Issue**
#19 制限によってボタンの活性/非活性を切り替える
#25 チャットの文字数制限
#30#37 入力禁止文字の制限（禁則文字、絵文字等）

### **対応内容**
- 利用者名とルーム名は、半角/全角英数字、ひらがな、カタカナ、漢字以外の入力を制限するようにした
- チャットの入力は、「'」「\」の入力のみを制限し、200文字の入力上限を加えた
- 制限した文字種を入力、もしくは上限を超える文字数の入力があった場合にボタンを非活性に切り替えるようにした
- ボタンデザインで、非活性状態は薄く、活性状態でマウスホバーした場合は濃く表示するようにした

### **動作確認**
利用者名とルーム名には、半角/全角英数字、ひらがな、カタカナ、漢字を入力するとボタンが活性状態になる
半角/全角英数字、ひらがな、カタカナ、漢字以外の記号などを入力した場合はボタンが非活性状態になる
チャットは「'」「\」を入力した場合は、送信ボタンが非活性になる

### **レビューポイント**
なし

2023-03-06 06:40 UTC, T-Iwasaki-R commented
全体的にif文が冗長です。
複数条件でreturnが同じな場合はelse if を複数設けるのではなく一つのif文で&& や || を使って条件式をまとめて処理するように修正お願いします。

2023-03-06 07:40 UTC, RuiFujita commented
||を用いて条件をまとめました。
確認よろしくお願いいたします。

2023-03-07 00:44 UTC, T-Iwasaki-R requested changes

2023-03-07 00:44 UTC, T-Iwasaki-R commented on frontend/src/component/ChatSpace.tsx
> +    if (message.length === 0 || message.length > messageMaxLength || messageRegex.test(message)) {
第一フェーズのソースコードレビュー前確認の際にも石川さんから指摘ありましたが、JS/TSのStringは空文字の時にはfalse、一文字でもあればtrueが返されるのでmessage.lengthのみでOKで === 0は不要です。
直感的に実装しているとよく見落としがちな処理なので判定分を実装するときは意識してみてください。

2023-03-07 01:30 UTC, T-Iwasaki-R commented
利用者名とルーム名について、スペースが含まれていると登録ができないようになっています。
スペースのみの入力は非活性で、スペースが混在している場合は登録できるように修正をお願いします。

2023-03-07 04:23 UTC, RuiFujita commented
userName.length===0
roomName.length===0
message.length===0
以上の条件式の===0を削除しました。また、論理否定演算子！をつけて空文字の場合にボタンを非活性にするようにしました。
スペースの制御は、新たに空白文字の正規表現を加えて、空白文字のみ入力した場合にボタンを非活性にするようにしました。
確認よろしくお願いいたします。

2023-03-07 05:01 UTC, T-Iwasaki-R commented
> userName.length===0 roomName.length===0 message.length===0 以上の条件式の===0を削除しました。また、論理否定演算子！をつけて空文字の場合にボタンを非活性にするようにしました。 スペースの制御は、新たに空白文字の正規表現を加えて、空白文字のみ入力した場合にボタンを非活性にするようにしました。 確認よろしくお願いいたします。

修正確認しました。対応ありがとうございます。

2023-03-07 05:06 UTC, T-Iwasaki-R requested changes

2023-03-07 05:06 UTC, T-Iwasaki-R commented on frontend/src/component/ChatSpace.tsx
> +    axios.get(url + '/chat_log', {
変数と文字列を連結させる際には+での連結ではなくテンプレートリテラルを使用する形で記載をお願いします。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals

2023-03-07 06:02 UTC, RuiFujita commented
変数+文字列で書いていた部分をすべてテンプレートリテラルの形式に修正しました。
加えて、CreateRoom.tsxにてresponseを使用していない個所がありましたので、削除しました。

2023-03-07 07:27 UTC, T-Iwasaki-R commented
> 変数+文字列で書いていた部分をすべてテンプレートリテラルの形式に修正しました。 加えて、CreateRoom.tsxにてresponseを使用していない個所がありましたので、削除しました。

確認しました。対応ありがとうございます。

2023-03-07 07:28 UTC, merged