サービスの公開
RuiFujita/web_chat_app pull request #4
Opened 2023-03-17 07:49 UTC by RuiFujita

### **レビュー希望納期**
2023/03/22

### **Issue**
アプリを利用する際に、ローカルに環境を構築する必要があった。

### **対応内容**
URLにアクセスするだけでアプリを利用できるようにした。
対応に付随して以下のエラーが発生したため解消した。
- ホーム画面に遷移した際にルーム一覧が取得できない。
- ルームを作成できない。
- チャット履歴が取得できない。
- チャットを送信できない。
- ルーム名を編集しても反映されない。

エラーの解消方法としては、axiosを使用している部分のパスを絶対パスから相対パスに変更した。
ルーム作成のエラーについてはSQL文に誤りがあったため、上の方法に加えてSQL文も修正した。

### **レビューポイント**
なし
c20a0c1bb3924f9e1c6a3267aa3bcf249a4167f2

2023-03-17 08:28 UTC, T-Iwasaki-R commented
サービス公開に関するPRだと思いますが、ルーム削除機能も含まれていませんか？

2023-03-22 01:35 UTC, RuiFujita commented
> サービス公開に関するPRだと思いますが、ルーム削除機能も含まれていませんか？

朝会にていただいたアドバイス通りに、ルーム削除機能の実装部分を削除しました。
確認よろしくお願いいたします。
[e124d27](https://github.com/RuiFujita/web_chat_app/pull/4/commits/e124d277012d56c954502a732ce5a48aa137d2bd)

2023-03-22 01:59 UTC, T-Iwasaki-R requested changes

2023-03-22 01:59 UTC, T-Iwasaki-R commented on backend/database.ts
> +  connection.query(`INSERT INTO room_info (room_name, is_deleted) VALUES ('${roomName}', 0)`, function (error: any, results: []) {
ここもルーム削除機能に関する実装ではないでしょうか？

2023-03-22 04:05 UTC, RuiFujita commented on backend/database.ts
> +  connection.query(`INSERT INTO room_info (room_name, is_deleted) VALUES ('${roomName}', 0)`, function (error: any, results: []) {
> ここもルーム削除機能に関する実装ではないでしょうか？

該当箇所を削除しました。
確認よろしくお願いします。
[0a28352](https://github.com/RuiFujita/web_chat_app/pull/4/commits/0a283528054235feca4587afcccb6513f5dfabf6)

2023-03-22 04:23 UTC, T-Iwasaki-R commented
プルリクエストのコメントに本対応の確認方法について記載してください。
どこにアクセスすることが可能なのか、どの操作の動作が確認できることで今回の対応が完了していることが分かるのかの観点で記載してみてください。

2023-03-24 02:42 UTC, RuiFujita commented
> プルリクエストのコメントに本対応の確認方法について記載してください。 どこにアクセスすることが可能なのか、どの操作の動作が確認できることで今回の対応が完了していることが分かるのかの観点で記載してみてください。

アクセス先を記載しました。
発生したエラーに対応した部分を確認できるように確認方法を追記しました。

2023-03-24 03:24 UTC, T-Iwasaki-R commented
ルームの作成、メッセージの送信時に500エラーが発生しています。

2023-03-24 04:10 UTC, RuiFujita commented
> ルームの作成、メッセージの送信時に500エラーが発生しています。

ルーム削除機能を実装した際、データベースのルーム情報を管理するテーブルにis_deletedを追加したため、SQL文に誤りがあるというエラーでした。テーブルのis_deletedを削除しましたので、ルーム作成は可能だと思います。
メッセージ送信時のエラーは再現できませんでした。

2023-03-24 05:21 UTC, T-Iwasaki-R commented
> > ルームの作成、メッセージの送信時に500エラーが発生しています。
> 
> ルーム削除機能を実装した際、データベースのルーム情報を管理するテーブルにis_deletedを追加したため、SQL文に誤りがあるというエラーでした。テーブルのis_deletedを削除しましたので、ルーム作成は可能だと思います。 メッセージ送信時のエラーは再現できませんでした。

最新の環境で動作を確認したところルーム作成メッセージ送信どちらもできていることが確認できました。
おそらくルーム作成時点で500エラーで落ちてしまったせいでメッセージ送信もできなかったものと思われます。

2023-03-24 05:28 UTC, T-Iwasaki-R approved these changes

2023-03-24 05:29 UTC, merged